extends RefCounted
func tags() -> Array: return ["unit","gameplay","deterministic"]
func run(t: TestContext,_tree: SceneTree) -> void:
 var db:=GameDatabase.new()
 var run:=RunController.new(db,321)
 var gem:=run.gems.add(Vector2(200,0),5,run.map)
 run.spatial.begin_tick()
 run.spatial.insert(SpatialWorld.GEM,gem,run.gems.positions[gem])
 var modifier:=WeaponModifiers.new()
 modifier.utility(run,db.table("v3_weapons").black_hole,Vector2.ZERO,100,1,"weapon:black_hole")
 t.equal(run.gems.magnet_count,1,"black hole uses gem query")
 var before:=run.gems.positions[gem].length()
 run.gems.tick_magnets(Vector2.ZERO,run.map)
 t.check(run.gems.positions[gem].length()<before,"gem pull moves simulation pickup")
 run.gems.take(gem)
 t.equal(run.gems.magnet_count,0,"pickup clears pull dense membership")
 var reused:=run.gems.add(Vector2(200,0),5,run.map)
 t.equal(run.gems.magnet_sparse[reused],-1,"reused gem has no stale magnet state")
 var id:=run.enemies.spawn(0,Vector2(30,0),{"hp":100,"radius":18})
 modifier.on_hit(run.enemies,id,Vector2.ZERO,db.table("v3_weapons").sonic_wave)
 t.check(run.enemies.impulses[run.enemies.slot(id)].x>0,"sonic wave actual knockback")
 run.map.rooms=[Rect2(-100,-100,200,200)]
 run.map.corridors.clear()
 run.map.kinds=["safe"]
 run.projectiles.add(Vector2(90,0),Vector2(1200,0),1,"weapon:wall_bounce_blaster",0,2)
 run.spatial.begin_tick()
 run.projectiles.tick(run.enemies,run.spatial,run.damage,run.map)
 var p:=run.projectiles.dense[0]
 t.check(run.projectiles.velocities[p].x<0,"wall projectile reflection")
 var seeking:=ProjectileWorld.new()
 seeking.add(Vector2.ZERO,Vector2.UP*100,1,"weapon:drone_bit",0,0,true)
 run.spatial.insert(SpatialWorld.ENEMY,id,Vector2(30,0))
 seeking.tick(run.enemies,run.spatial,run.damage,run.map)
 t.check(seeking.velocities[0].x>0,"drone seeker steers toward query target")
 run.deployments.add(Vector2(30,0),50,10,"weapon:crystal_mine",3,db.table("v3_weapons").crystal_mine)
 for tick in range(29): run.deployments.tick(run.enemies,run.spatial,run.damage)
 t.equal(run.enemies.hp[run.enemies.slot(id)],100.0,"mine arm delay")
 run.deployments.tick(run.enemies,run.spatial,run.damage)
 t.equal(run.enemies.hp[run.enemies.slot(id)],90.0,"armed mine centralized damage")
 t.equal(run.deployments.count,0,"mine consumed exactly once")
 var main:=run.deployments
 run.deployments.add(Vector2.ZERO,50,1,"weapon:frost_wall",1,db.table("v3_weapons").frost_wall)
 var clock:=main.remaining[main.dense[0]]
 run.warp.enter(run,0)
 t.check(run.deployments!=main,"warp has separate deployment world")
 run.warp.leave(run)
 t.check(run.deployments==main,"main deployments restored")
 t.equal(main.remaining[main.dense[0]],clock,"main deployment frozen during warp")
 var beam_world := DeployWorld.new()
 var beam_damage := DamageSystem.new()
 beam_world.add(Vector2.ZERO,20,30,"weapon:shrine_beam",8,db.table("v3_weapons").shrine_beam,Vector2.RIGHT)
 for tick in range(121): beam_world.tick(run.enemies,run.spatial,beam_damage)
 t.equal(beam_damage.total(),30.0,"stationary shrine beam pulses sum to cast damage")
 t.check(beam_world.count>0,"beam persists between pulses")
 t.equal(db.table("v3_weapons").magma_core.archetype,"deploy","magma leaves persistent floor")
 var gravity := DeployWorld.new()
 run.enemies.impulses[run.enemies.slot(id)]=Vector2.ZERO
 gravity.add(Vector2.ZERO,100,3,"weapon:black_hole",3,db.table("v3_weapons").black_hole)
 gravity.tick(run.enemies,run.spatial,run.damage)
 t.check(run.enemies.impulses[run.enemies.slot(id)].x<0,"deployed singularity applies actual pull")
 var poisoned := RunController.new(db,457)
 var boss:=poisoned.enemies.spawn(-3,Vector2.ZERO,{"hp":1,"damage":100,"radius":55},1,true)
 var slot:=poisoned.enemies.slot(boss)
 poisoned.enemies.poison[slot]=10
 poisoned.enemies.periodic[slot]=1
 poisoned.enemies.warning[slot]=2
 poisoned.enemies.action[slot]=100
 var hp:=poisoned.state.player.hp
 poisoned.pipeline.tick(poisoned,Vector2.ZERO)
 t.equal(poisoned.state.phase,"CLEAR","lethal status resolves final-boss clear before AI")
 t.equal(poisoned.state.player.hp,hp,"dead poisoned boss cannot attack")
 t.equal(poisoned.damage.totals["status:poison"],1.0,"status attribution clamps to actual HP")
 var world:=EnemyWorld.new()
 var entity:=world.spawn(0,Vector2.ZERO,{"hp":100})
 var index:=world.slot(entity)
 world.poison[index]=90
 world.periodic[index]=1
 var timers:=StatusSystem.new()
 var attribution:=DamageSystem.new()
 timers.tick(world,PlayerState.new(),1,attribution)
 t.equal(world.periodic[index],30,"status owner arms periodic timer")
 for tick in range(2,31): timers.tick(world,PlayerState.new(),tick,attribution)
 t.equal(attribution.total(),2.0,"poison fires once in thirty fixed ticks")
 timers.tick(world,PlayerState.new(),31,attribution)
 t.equal(attribution.total(),4.0,"poison period follows fixed ticks")
