extends RefCounted
func tags() -> Array: return ["unit","gameplay","UI","iOS","release"]
func run(t: TestContext,tree: SceneTree) -> void:
 tree.root.size=Vector2i(1280,720)
 var app=load("res://scenes/Main.tscn").instantiate()
 app.save_path="user://qa_ui_regression.save"
 for p in [app.save_path,app.save_path+".bak",app.save_path+".tmp"]: DirAccess.remove_absolute(ProjectSettings.globalize_path(p))
 tree.root.add_child(app)
 app.set_physics_process(false)
 await tree.process_frame
 var ui: UIController=app.controller
 ui.show_character()
 ui.show_setup()
 ui.view.node("RunSetup","Seed").text="0"
 ui.validate_seed()
 t.check(ui.view.node("RunSetup","Start").disabled,"invalid seed explains disabled start")
 ui.view.node("RunSetup","Seed").text="60606"
 ui.start_selected()
 t.equal(app.run.state.seed_value,60606,"UI setup starts reproducible seed")
 var start_run=app.run
 ui.start_selected()
 t.check(app.run==start_run,"start transition duplicate rejected")
 var touch:=InputEventScreenTouch.new()
 touch.pressed=true; touch.index=0; touch.position=Vector2(100,300)
 app.touch._input(touch)
 var drag:=InputEventScreenDrag.new()
 drag.index=0; drag.position=Vector2(165,300)
 app.touch._input(drag)
 t.check(app.touch.direction.x>.9,"touch moves when gameplay owns input")
 ui.pause_toggle()
 t.equal(app.touch.direction,Vector2.ZERO,"pause neutralizes joystick")
 t.equal(app.touch.finger,-1,"pause releases finger")
 t.check(not app.touch.enabled,"modal disables joystick")
 var tick: int=app.run.state.tick
 app.run.pipeline.tick(app.run,Vector2.RIGHT)
 t.equal(app.run.state.tick,tick,"paused simulation cannot tick")
 ui.open_menu("SettingsScreen")
 t.equal(app.run.state.phase,"PAUSED","pause settings retain paused simulation")
 ui.back()
 t.equal(ui.current,"PauseMenu","settings back restores pause")
 ui.pause_toggle()
 app.run.state.progression.choices=[["weapons","magic_bolt"]]
 app.run.state.phase="LEVEL_UP"
 ui.sync_phase()
 ui.choose(9)
 t.equal(ui.current,"LevelUpPanel","invalid choice cannot dismiss modal")
 ui.pause_toggle()
 ui.pause_toggle()
 t.equal(app.run.state.phase,"LEVEL_UP","pause resumes exact suspended choice")
 var level: int=app.run.state.progression.weapons.magic_bolt
 ui.choose(0)
 ui.choose(0)
 t.equal(app.run.state.progression.weapons.magic_bolt,level+1,"double choice applies once")
 var gate:=UIActionGate.new()
 t.check(gate.allow("buy",1000),"first action allowed")
 t.check(not gate.allow("buy",1050),"double tap rejected")
 t.check(gate.allow("buy",1400),"later intentional action allowed")
 app.run.state.phase="RUNNING"
 var signature: int=app.run.signature()
 t.check(not app.run.warp.enter(app.run,-1),"invalid warp rejected")
 t.equal(app.run.signature(),signature,"invalid warp leaves world untouched")
 ui.pause_toggle()
 t.check(not app.run.warp.enter(app.run,0),"paused warp rejected")
 ui.confirm("終了しますか",ui.end_run)
 ui.back()
 t.equal(app.run.state.phase,"PAUSED","cancel end preserves run")
 ui.pause_toggle()
 ui.show_shop()
 app.saves.data.profile.currency=0
 ui.shop_index=ui.shop_ids.find(["meta_upgrades","base_hp"])
 ui.update_shop()
 t.check(ui.view.node("ShopScreen","Buy").disabled,"unaffordable shop disabled")
 t.check(ui.view.node("ShopScreen","Reason").text.contains("不足"),"unaffordable reason visible")
 app.saves.data.progression.meta.base_hp=int(app.db.table("meta_upgrades").base_hp.max_level)
 ui.update_shop()
 t.check(ui.view.node("ShopScreen","Buy").disabled,"max shop disabled")
 t.check(ui.view.node("ShopScreen","Reason").text.contains("最大"),"max reason visible")
 var broken:=SaveRepository.new("user://missing-ui-parent/failed.save","user://qa_missing.save")
 broken.data.profile.currency=10000
 var before:=broken.data.duplicate(true)
 t.check(not broken.buy_meta("base_hp",app.db.table("meta_upgrades").base_hp),"failed save rejects purchase")
 t.equal(broken.data,before,"failed purchase rolls back currency and level")
 var corrupt: String="user://qa_ui_corrupt.save"
 for p in [corrupt,corrupt+".bak",corrupt+".tmp",corrupt+".corrupt"]: DirAccess.remove_absolute(ProjectSettings.globalize_path(p))
 FileAccess.open(corrupt,FileAccess.WRITE).store_string("broken-original")
 var protected:=SaveRepository.new(corrupt,"user://qa_missing.save")
 t.check(protected.blocked_load,"unrecoverable malformed save is protected")
 protected.mark_dirty()
 t.check(not protected.flush(),"corrupt original cannot be overwritten")
 t.equal(FileAccess.get_file_as_string(corrupt),"broken-original","corrupt original retained byte-for-byte")
 FileAccess.open(corrupt+".bak",FileAccess.WRITE).store_string(JSON.stringify(SaveMigration.new().defaults()))
 t.check(protected.recover_blocked(),"retry reloads validated recovery data")
 t.check(not protected.blocked_load,"successful recovery unblocks save")
 t.equal(FileAccess.get_file_as_string(corrupt+".corrupt"),"broken-original","recovery retains damaged original bytes")
 var notifications:=UINotifications.new()
 for n in range(20): notifications.add("loot","回収",1,1000)
 t.equal(notifications.entries.size(),1,"notification deduplicates")
 notifications.add("boss","ボス",3,1000)
 for n in range(20): notifications.add(str(n),"装飾",0,1000)
 t.check(notifications.entries.size()<=4,"notification buffer bounded")
 t.equal(notifications.current(1100),"ボス","important notification cannot be crowded out")
 t.equal(notifications.current(7000),"","notification expires")
 var saved: String=app.saves.data.settings.profile
 app.set_temporary_profile("ios_ultra")
 t.equal(app.saves.data.settings.profile,saved,"temporary quality never overwrites saved preference")
 t.equal(app.effective_profile(),"ios_ultra","effective override shown separately")
 app.set_temporary_profile("")
 t.equal(app.effective_profile(),saved,"temporary override resumes preference")
 app.run.state.phase="CLEAR"
 ui.sync_phase()
 ui.continue_endless(); ui.continue_endless()
 t.check(app.run.state.endless and app.run.state.phase=="RUNNING","clear/endless duplicate safe")
 ui.end_run(); var runs: int=app.saves.data.profile.runs; ui.end_run()
 t.equal(app.saves.data.profile.runs,runs,"result settlement exactly once")
 t.check(ui.result_text().contains("最終Lv"),"result includes final build progression")
 ui.home(); ui.home()
 t.equal(ui.current,"TitleScreen","result home idempotent")
 t.equal(app.run,null,"title has no gameplay continuation")
 var area:=SafeArea.new()
 t.check(area.logical_rect(Vector2(844,390),Vector2(2532,1170),Rect2i(132,0,2268,1107)).has_area(),"3x phone safe area")
 t.check(area.logical_rect(Vector2(1280,720),Vector2.ZERO,Rect2i()).has_area(),"missing platform metrics gracefully fall back")
 app.queue_free()
 await tree.process_frame
 for p in ["user://qa_ui_regression.save","user://qa_ui_regression.save.bak","user://qa_ui_regression.save.tmp",corrupt,corrupt+".bak",corrupt+".corrupt"]: DirAccess.remove_absolute(ProjectSettings.globalize_path(p))
